{% set name = "rastervision-core" %}
{% set version = "0.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rastervision_core-{{ version }}.tar.gz
  sha256: 46db65e773043f1ff42d9ade93c2089284eeaf48ab23df26c859758dd83847ba
  patches:
    - 0001-fix-imports.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rastervision=rastervision.core.cli:predict

requirements:
  host:
    - pip
    - python >=3.0
    - opencv
  run:
    - python >=3.0
    - opencv
    - imageio ==2.3.*
    - mask-to-polygons ==0.0.2
    - numpy
    - pillow
    - pyproj ==2.6.*
    - pystac
    - rasterio
    - rastervision-pipeline
    - scikit-learn
    - shapely ==1.6.*
    - supermercado ==0.0.*


test:
  imports:
    - rastervision
#  commands: removed due to incompatibility with opencv
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/azavea/raster-vision
  summary: A rastervision plugin that adds geospatial machine learning pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psortos
    - mxr-conda
